name: Delete Stale Branches Automatically

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  clean_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Stale Branch Cleaner
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          GITHUB_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          python tools/branch_cleanup.py
